service: fullstack_blogging

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
